development:
  host: localhost
  database: rails_api_development
  autocreate_indexes: true

test:
  host: localhost
  database: rails_api_test
  autocreate_indexes: true

# set these environment variables on your prod server
production:
  autocreate_indexes: true

  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
