source "http://rubygems.org"

# lightweight ruby http framework
gem "sinatra"

# mongoid ORM for mongoDB
gem "sinatra-mongoid", :require => "sinatra/mongoid"

# geolocation
gem "geokit"

# geolocation for mongoid
gem "mongoid_geo", :git => "git://github.com/kristianmandrup/mongoid-geo.git"

# sinatra asked for this
gem "SystemTimer"

# mongoDB asked for this
gem "bson_ext"

# debugger
gem 'ruby-debug'
